### ISSUE TITLE
Parameters are not passed to the launched application

### ISSUE THREAD

**Issue by countfloyd** [edvin/fxlauncher#1]
If I want parameters passed to the launched application, I can pass them to fxlauncher.Launcher but it doesn't pass them through.

I solved this by adding this line before the app.start(primaryStage); in Launcher.java:

```
ParametersImpl.registerParameters(app, getParameters());
```

I know this uses a com.sun class but I didn't see any other way to do it.

**Comment by edvin** [comment]
Thanks for reporting and suggesting a workaround. I can't see any other way either, so I will include this in the upcoming 1.0.7 release.

**Comment by edvin** [comment]
By the way, I've found a way to avoid using private API for this. It seems that `Application.Parameters` are indeed public and part of the JavaFX API, so I would simply need to wrap the result from `getParameters()` in my own implementation of `Application.Parameters` and the `com.sun` dependency is avoided.

It seems there is a use case for configuring parameters in the launcher itself, so I'm going to add support for that as well :)
