### ISSUE TITLE
Manifest and .war dependency

### ISSUE THREAD

**Issue by carlosmonterocanabal** [edvin/fxlauncher#10]
I think that this test 

> if (!Files.isDirectory(file) && file.toString().endsWith(".jar") && !file.getFileName().toString().startsWith("fxlauncher"))

into CreateManifest class is not correct if you have any war as dependency. 

In my case, I have a app that runs a embedded jetty with a war (that it's a dependency of the project).

What do you think? Could you create a dependencyExtension param and by default it's only ".jar"?

I'm updating all my projects to use this amazing lib and removing from jnlp, so thank you so much :)

**Comment by edvin** [comment]
Ah, I didn't think of that. Do you think it's sufficient to check for .jar + .war, or do we need to make this configurable? I guess it would be better to check for .jar + .war anyways. What would you prefer?

**Comment by carlosmonterocanabal** [comment]
I think that .jar and .war it's ok.

**Comment by edvin** [comment]
Great! I added it now. Do you have a workaround or do you need a release with just this feature?

**Comment by carlosmonterocanabal** [comment]
I will launch in 2-3 days a new version of my app. But i can do a internal release with the change if you dont make a release only for this. Thank you and keep the great work 👍🏼

**Comment by edvin** [comment]
All right, if you can just build locally, I'll hold off on the release until we have some more features :)

**Comment by serzh-f** [comment]
Hi edvin! How about to add configuration, which can add custom extensions?

For example I need to add ".pdf" file in my fxlauncher folder. Can you help, please?

**Comment by edvin** [comment]
You can add `--include-extensions=pdf` as a parameter to the `CreateManifest` command :)

**Comment by serzh-f** [comment]
Thanks,
But I use fxlauncher with gradle. Where is it?
