### ISSUE TITLE
Allow to dynamically set the download url

### ISSUE THREAD

**Issue by tobrob** [edvin/fxlauncher#108]
Hello,

we really like the fxlauncher framework. It enables us to avoid having to update our javafx clients manually.

Is it possible to set the uri in our custom ui, e.g. using a textfield or reading it from java preferences.
If this would be possible, we could only have one single JavaFx-Client.exe that we can install on multiple devices. And every device could use a different local network uri to load its content.

Do you know a way to achieve this?

Thanks very much in advance. :)

**Comment by edvin** [comment]
You might be able to use the `app` and `uri` parameters, take a look in the README for more details. Does that work for you?

**Comment by rppimenta** [comment]
Hi,

I need the same @tobrob solution.
I may not be understanding the correct operation of --app and --uri.
I'm not using the app.xml built into the launcher. I was only using the --uri parameter with the remote url, but in cases where the machine is completely off, the app will not open.
I would like to configure the --uri remote, and pass the --app a local file? So in cases where --uri fails, it uses the --app local file?

I'm sorry if I did not understand the correct operation.

**Comment by tobrob** [comment]
Thanks for the answer. The uri parameter might be a workaround we could use. 
This would be a bit unconvenient however. We would have to manually create a link on the desktop and set the uri-parameter there or create multiple releases with a preconfigured uri.

What we would prefer is to enable the user to configure the uri (or ip) using a costum ui. As I see there's no easy way to achieve this? Is there?

Thanks so much

**Comment by edvin** [comment]
Why don't you just build multiple versions, one for each app? :)

**Comment by tobrob** [comment]
Ok. Then that's what we are going to do. 
We will create a parameterized build to be able to create a client with a pre-configured uri for each deployment.
