### ISSUE TITLE
Update probleme

### ISSUE THREAD

**Issue by camaragit** [edvin/fxlauncher#115]
Hi edvin this my probleme when i launch my app it does not update and if i check the fxlauncher.log i can see this : AVERTISSEMENT: Unable to update manifest from http://212.71.244.7/deploy/app.xml
javax.xml.bind.DataBindingException: javax.xml.bind.MarshalException
 - with linked exception:
[java.io.FileNotFoundException: C:\Program Files (x86)\Kollere\app\.\DashBoard.Main.xml (Acc鳠refus骝
	at javax.xml.bind.JAXB._marshal(JAXB.java:574)
	at javax.xml.bind.JAXB.marshal(JAXB.java:332)
	at fxlauncher.AbstractLauncher.syncManifest(AbstractLauncher.java:222)
	at fxlauncher.AbstractLauncher.updateManifest(AbstractLauncher.java:92)
	at fxlauncher.Launcher.lambda$start$0(Launcher.java:137)
	at java.lang.Thread.run(Thread.java:748)
Caused by: javax.xml.bind.MarshalException
 - with linked exception:
[java.io.FileNotFoundException: C:\Program Files (x86)\Kollere\app\.\DashBoard.Main.xml (Acc鳠refus骝
	at com.sun.xml.internal.bind.v2.runtime.MarshallerImpl.createXmlOutput(MarshallerImpl.java:215)
	at com.sun.xml.internal.bind.v2.runtime.MarshallerImpl.marshal(MarshallerImpl.java:236)
	at javax.xml.bind.JAXB._marshal(JAXB.java:572)
	... 5 more
Caused by: java.io.FileNotFoundException: C:\Program Files (x86)\Kollere\app\.\DashBoard.Main.xml (Acc鳠refus驍
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:101)
	at com.sun.xml.internal.bind.v2.runtime.MarshallerImpl.createXmlOutput(MarshallerImpl.java:210)
	... 7 more
can you please help me to fix this. Sorry for my bad english

**Comment by edvin** [comment]
It looks like you have given a weird path to where `DashBoard.Main.xml` is located. Do you have your source code anywhere public?

**Comment by camaragit** [comment]
Thank you Edvin for your reply here is my pom.xml :

<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>groupId</groupId>
    <artifactId>kollere_maven</artifactId>
    <version>1.0-SNAPSHOT</version>
    <dependencies>
        
        
        <dependency>
            <groupId>com.jfoenix</groupId>
            <artifactId>jfoenix</artifactId>
            <version>1.1.0</version>
        </dependency>
        <dependency>
            <groupId>javax.ws.rs</groupId>
            <artifactId>jsr311-api</artifactId>
            <version>1.1.1</version>
        </dependency>
        <dependency>
            <groupId>no.tornado</groupId>
            <artifactId>fxlauncher</artifactId>
            <version>1.0.16</version>
        </dependency>
        
        
        <dependency>
            <groupId>com.sun.jersey</groupId>
            <artifactId>jersey-bundle</artifactId>
            <version>1.8</version>
        </dependency>
        <dependency>
            <groupId>org.codehaus.jackson</groupId>
            <artifactId>jackson-jaxrs</artifactId>
            <version>1.9.0</version>
        </dependency>
        
        <dependency>
            <groupId>de.jensd</groupId>
            <artifactId>fontawesomefx</artifactId>
            <version>8.9</version>
        </dependency>
        <dependency>
            <groupId>org.controlsfx</groupId>
            <artifactId>controlsfx</artifactId>
            <version>8.40.11</version>
        </dependency>

    </dependencies>
    <properties>
        
        <app.filename>FxlDemo</app.filename>

        
        <app.mainClass>no.tornado.FxlDemo</app.mainClass>

        
        <app.cacheDir>USERLIB/FxlDemo</app.cacheDir>

        
        <app.parameters>--myOption=myValue --myOtherOption=myOtherValue</app.parameters>

        
        <app.vendor>AJIT</app.vendor>

        
        <app.version>1.0</app.version>

        
        <app.url>http://212.71.244.7/deploy/</app.url>

        
        <app.deploy.target>root@212.71.244.7:/var/www/html/deploy/</app.deploy.target>

        
        <app.dir>${project.build.directory}/app</app.dir>

        
        <app.installerdir>${project.build.directory}/installer</app.installerdir>

        
        <app.acceptDowngrade>false</app.acceptDowngrade>

        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <build>
        <plugins>
            
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <version>2.6</version>
                <configuration>
                    <outputDirectory>${app.dir}</outputDirectory>
                </configuration>
            </plugin>
            
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-dependency-plugin</artifactId>
                <version>2.10</version>
                <configuration>
                    <excludeScope>provided</excludeScope>
                    <outputDirectory>${app.dir}</outputDirectory>
                    <stripVersion>true</stripVersion>
                </configuration>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>copy-dependencies</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>exec-maven-plugin</artifactId>
                <version>1.4.0</version>
                
                <executions>
                    <execution>
                        <id>create-manifest</id>
                        <phase>package</phase>
                        <goals>
                            <goal>java</goal>
                        </goals>
                        <configuration>
                            <mainClass>fxlauncher.CreateManifest</mainClass>
                            <arguments>
                                <argument>${app.url}</argument>
                                <argument>${app.mainClass}</argument>
                                <argument>${app.dir}</argument>
                                <argument>--cache-dir=${app.cacheDir}</argument>
                                <argument>--accept-downgrade=${app.acceptDowngrade}</argument>
                                <argument>--include-extensions=jpg</argument>
                                <argument>${app.parameters}</argument>
                            </arguments>
                        </configuration>
                    </execution>
                    
                    <execution>
                        <id>embed-manifest-in-launcher</id>
                        <phase>package</phase>
                        <goals>
                            <goal>exec</goal>
                        </goals>
                        <configuration>
                            <executable>jar</executable>
                            <workingDirectory>${app.dir}</workingDirectory>
                            <arguments>
                                <argument>uf</argument>
                                <argument>fxlauncher.jar</argument>
                                <argument>app.xml</argument>
                            </arguments>
                        </configuration>
                    </execution>

                    <execution>
                        <id>installer</id>
                        <phase>install</phase>
                        <goals>
                            <goal>exec</goal>
                        </goals>
                        <configuration>
                            <executable>javapackager</executable>

                            <arguments>
                                <argument>-deploy</argument>
                                <argument>-native</argument>
                                <argument>-outdir</argument>
                                <argument>${app.installerdir}</argument>
                                <argument>-outfile</argument>
                                <argument>${app.filename}</argument>
                                <argument>-srcdir</argument>
                                <argument>${app.dir}</argument>
                                <argument>-srcfiles</argument>
                                <argument>fxlauncher.jar</argument>
                                <argument>-appclass</argument>
                                <argument>fxlauncher.Launcher</argument>
                                <argument>-name</argument>
                                <argument>${project.name}</argument>
                                <argument>-title</argument>
                                <argument>${project.name}</argument>
                                <argument>-vendor</argument>

                                <argument>-BappVersion=${app.version}</argument>
                                <argument>-Bidentifier=${project.groupId}.${project.artifactId}</argument>
                            </arguments>
                        </configuration>
                    </execution>
                    
                    <execution>
                        <id>deploy-app</id>
                        <goals>
                            <goal>exec</goal>
                        </goals>
                        <configuration>
                            <executable>scp</executable>
                            <arguments>
                                <argument>-r</argument>
                                <argument>target/app/</argument>
                                <argument>${app.deploy.target}</argument>
                            </arguments>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.3</version>
                <configuration>
                    <source>1.8</source>
                    <target>1.8</target>
                </configuration>
            </plugin>
        </plugins>
    </build>

</project>
When launch the app with the executable(kollere_maven.exe) wich is generate in the target/\installer\bundles\kollere_maven  it works and apply the update. But if create package with inno Setup with that executable and install it on my computer the update does not apply and when look the fxlauncher.log it is this issue that i have. I thought that it is because that the fxlauncher does not accept the packaging with InnoSteup.

**Comment by camaragit** [comment]
Hi Edvin here is my project https://github.com/camaragit/kollere_maven.
