### ISSUE TITLE
How to execute additional services during app update

### ISSUE THREAD

**Issue by gabrielpaim** [edvin/fxlauncher#116]
Hi there,

I'm trying to use fxlauncher for our application, but I need to execute a database migration (among other stuff) during the app update progress. The whole update should also work "atomically" - if the migration for some reason fails, the update should also fallback and the previous application version should stand. In other words, I'd like to execute some logic with conditional result before syncing files during the update procedure. 

Have you guys ever thought about this? Has anyone faced something similar? Is there a way to still use FxLauncher for my app with this constraint?

Thank you, great job @edvin !

**Comment by edvin** [comment]
There is no support for that, so yeah, the HeadlessMainLauncher is probably your best bet. It would be possible to support a pre-update check, which would be allowed to download a jar and run a specific main method where you could perform the update and return false if no update should be done for example.

**Comment by gabrielpaim** [comment]
Alright, I'll take a look if this strategy is sufficient for my specific use case. 
I'll leave this open for a while, until I check that, ok?

Thank you!

**Comment by edvin** [comment]
Absolutely :)

**Comment by gabrielpaim** [comment]
Hi guys,

after understanding a bit better how does the launcher works, I managed to solve my problem this way:

- Implemented a CustomLauncher extended from AbstractLauncher (the same way as HeadlessMainLauncher)
- Added a gradle task to insert the CustomLauncher inside fxlauncher.jar and update the manifest from fxlauncher to use the main class inside this CustomLauncher
- Added a dependency of task deployApp to this new task

The above steps made possible to insert specific logic inside the update flow:

```
protected void process() throws Exception {
    syncManifest();
    
    if (executeCustomTask()) {
        parameters = new LauncherParams(parameters, getManifest());
        checkSSLIgnoreflag();
        updateManifest();
        syncFiles();
    }

    createApplicationEnvironment();
    launchApp();
}
```

As I also want to show some UI during this process, I'm thinking in reusing some of the default Launcher code to do so. However, I didn't understand how exactly the HeadlessMainLauncher could help me in this task, tough. Am I missing anything?

Thanks again, great stuff here, guys, it's helping us! ;)
