### ISSUE TITLE
Gradle multi module projects

### ISSUE THREAD

**Issue by SirWindfield** [edvin/fxlauncher#12]
I couldn't really figure out how to use fxlauncher in a Gradle project containing multiple modules. I added the needed gradle code to the build.gradle file of the parent project but it doesn't copy the build files from the modules to the output directory. Could you help me out please?

P.S.: I am relatively new to Java and coding in general. Sorry if this question is stupid.

**Comment by edvin** [comment]
Hi @SirWindfield - I'm no Gradle expert myself, having only used it to create the sample for fxlauncher (Maven guy here :), but I'm sure I'll figure it out. The way I assemble the artifacts in build/libs might not be the best approach either, so let me have a look at this tomorrow and get back to you, OK?

**Comment by edvin** [comment]
It would be helpful if you can share the project or at least the project skeleton as you have it right now as well :)

**Comment by SirWindfield** [comment]
Never mind, I just solved it. It works by default without changing anything specific in the gradle file itself. I just messed up and forgot to add a task for copying the files like you did in the example file. Sorry for the inconvenience 😞

**Comment by edvin** [comment]
Great :) No problem at all, I'll close the issue then. Please let me know if you run into any further issues.
