### ISSUE TITLE
Latest gradle plugin not published to http://plugins.gradle.org

### ISSUE THREAD

**Issue by nhajratw** [edvin/fxlauncher#122]
The most recent version of the gradle plugin is 1.0.16, but the current version is 1.0.19 ... is there a way to make the release to the gradle plugin repo automatic with each new version?

https://plugins.gradle.org/plugin/no.tornado.fxlauncher

**Comment by edvin** [comment]
I'm not sure how to affect plugins.gradle.org. Does anybody know?

**Comment by nhajratw** [comment]
It looks like you can use the Plugin Publishing Plugin ... I assume it was
used in the past to publish what's out there?
https://plugins.gradle.org/docs/publish-plugin

**Comment by edvin** [comment]
You're right, thanks a lot :) I published the latest version now :)
