### ISSUE TITLE
Main class not found with kotlin

### ISSUE THREAD

**Issue by andyalbert** [edvin/fxlauncher#136]
Hello, I'm trying to generate native apk, but unfortunately got this error: `java.lang.ClassNotFoundException: MyApp.kt`

and here is the build.gradle:
`plugins {
    id 'java'
    id 'org.jetbrains.kotlin.jvm' version '1.2.71'
    id "no.tornado.fxlauncher" version "1.0.20"
}

group 'com.church'
version '1.0-SNAPSHOT'

sourceCompatibility = 1.8

repositories {
    mavenCentral()
}

sourceSets {
    main.kotlin.srcDirs = ['src/main/kotlin', 'src/main/java']
    main.java.srcDirs = []
    test.kotlin.srcDirs = ['src/test/kotlin', 'src/test/java']
    test.java.srcDirs = ['src/test/kotlin', 'src/test/java']
}
dependencies {
    compile "org.jetbrains.kotlin:kotlin-stdlib-jdk8"
    compile 'no.tornado:tornadofx:1.7.17'
    compile 'org.xerial:sqlite-jdbc:3.23.1'
    testCompile group: 'junit', name: 'junit', version: '4.12'
}

compileKotlin {
    kotlinOptions.jvmTarget = "1.8"
}
compileTestKotlin {
    kotlinOptions.jvmTarget = "1.8"
}

fxlauncher {
    applicationUrl 'http://fxldemo.tornado.no/'
    applicationMainClass 'MyApp.kt'
//    deployTarget 'w48839@fxldemo.tornado.no:fxldemo'
}`

**Comment by edvin** [comment]
Please make a package for MyApp and reference the fully qualified package/class name in the `applicationMainClass` parameter :)
