### ISSUE TITLE
Cannot localize resource file. Problem with creating file.

### ISSUE THREAD

**Issue by Mistral** [edvin/fxlauncher#139]
I have 2 other problems:

1. Im using javaFX with springboot, after creation .deb package, application doesn't see fxml files in `resource` directory. When I copy `fxml` files to directory with classes - then it works.
2. My project use database sqlite. In first time database should be created automatic by hibernate. But I am getting error: Access deny. Application can't create file.

**Comment by edvin** [comment]
1. You must make sure that your build system copies your resources files to the classpath.
2. You haven't supplied nearly enough information to be able to debug this.

**Comment by Mistral** [comment]
Ok, all reported issues were my mistakes. Sorry for the inconvenience.
