### ISSUE TITLE
Loading and Updating scene customization

### ISSUE THREAD

**Issue by pablovilas** [edvin/fxlauncher#14]
Hello Edvin,

I'm wondering if it's possible to customize the loading and updating scenes.
This is the default loading scene:

![loading](https://cloud.githubusercontent.com/assets/1742196/16195965/4cbbd84c-36d2-11e6-8979-d1cd3b2a95a3.png)

and this is the updating scene:

![updating](https://cloud.githubusercontent.com/assets/1742196/16195979/57c23452-36d2-11e6-94fa-8a30f8aa3f35.png)

I think right now is possible to do some customization to the "updating" scene via app.xml. Would be awesome if we can provide both custom scenes or something like that.
Again, thanks.

**Comment by edvin** [comment]
Absolutely. I'll add support for customizing it completely, but it will have to wait for some days, I need to finish another project first.

**Comment by edvin** [comment]
In the mean time, you can customize some parts of the appearance in app.xml already:

```xml
<updateText>Updating...</updateText>
<updateLabelStyle>-fx-font-weight: bold;</updateLabelStyle>
<progressBarStyle>-fx-pref-width: 200;</progressBarStyle>
<wrapperStyle>-fx-spacing: 10; -fx-padding: 25;</wrapperStyle>
```

**Comment by pablovilas** [comment]
Sure, no problem. Just let me know if you need some help with testing.

**Comment by edvin** [comment]
Sorry for taking so long with this. My schedule is clearing up a bit, so I started looking at this now @pablovilas - do you think it would be adequate to let the user specify FXML-files to be used for the loading and updating-screens? I would then embed that FXML code inside the manifest. What do you think?

**Comment by pablovilas** [comment]
Hello Edvin, no problem... I completely understand. It will be excelent if you let the user specify FXML or why not a Scene class also (If you have some dynamic controls creation inside).
Thanks!

**Comment by edvin** [comment]
We could go for a complete scene graph, but that means embedding code inside the launcher as well. Might not be a big deal though, let me try it out and get back to you.

**Comment by edvin** [comment]
It might be hard to determine which classes needs to go inside the launcher, in case of inner classes and such. I think that would have to be offloaded to the user, so you actually have to define the class, and also the path to any resources that should be embedded inside the launcher.

**Comment by pablovilas** [comment]
Maybe if we just add more customization options is enough. For example a custom splash background and more stylable options. What do you think?

**Comment by edvin** [comment]
I have another idea: Create two interfaces that can be implemented for the two scenes and then you create a separate project where you include `fxlaunchar.jar` only as a compile time dependency. The result jar can be referenced from the `createManifest` step, where it is automatically embedded into the launcher. Should be pretty easy to use, and also easy to implement. Or is that too much?

**Comment by edvin** [comment]
This actually means that we can clean up the default UI as well, by delivering it through this `UIProvider` interface:

```java
public class DefaultUIProvider implements UIProvider {
	private ProgressBar progressBar;

	public Parent createLoader() {
		StackPane root = new StackPane(new ProgressIndicator());
		root.setPrefSize(200, 80);
		root.setPadding(new Insets(10));
		return root;
	}

	public Parent createUpdater(FXManifest manifest) {
		progressBar = new ProgressBar();
		progressBar.setStyle(manifest.progressBarStyle);

		Label label = new Label(manifest.updateText);
		label.setStyle(manifest.updateLabelStyle);

		VBox wrapper = new VBox(label, progressBar);
		wrapper.setStyle(manifest.wrapperStyle);

		return wrapper;
	}

	public void updateProgress(double progress) {
		progressBar.setProgress(progress);
	}
}
```

**Comment by edvin** [comment]
This is the Interface as I imagine it:

```java
public interface UIProvider {
	/**
	 * Create the Node that will be displayed while the launcher is loading resources,
	 * before the update process starts. The default implementation is an intdeterminate
	 * progress indicator, but you can return any arbitrary scene graph.
	 *
	 * @return The launcher UI
	 */
	Parent createLoader();

	/**
	 * Create the Node that will be displayed while the launcher is updating resources.
	 *
	 * This Node should update it's display whenever the {@link #updateProgress(double)}
	 * method is called.
	 *
	 * @see #updateProgress(double)
	 * @return The updater Node
	 */
	Parent createUpdater(FXManifest manifest);

	/**
	 * Called when the update/download progress is changing. The progress is a value between
	 * 0 and 1, indicating the completion rate of the update process.
	 *
	 * @param progress A number between 0 and 1
	 */
	void updateProgress(double progress);
}
```

**Comment by pablovilas** [comment]
I really like the idea of having interfaces but I'm not sure if creating another project it's a little too much. If we can only implement that interfaces inside the current project would be awesome but I think it's not possible because how fxlauncher works. Anyway it's an optional feauture so... you do that if you need to.

**Comment by edvin** [comment]
Sure, it is absolutely possible to implement it inside the current project as well. Let me flesh this out and I'll show you :)

**Comment by pablovilas** [comment]
Perfect!, please let me know if you need some help with testing

**Comment by edvin** [comment]
I have it working, but it is cumbersome for the user to set it up. I want to think about this for a little while and try some other approaches first, OK? :)

**Comment by pablovilas** [comment]
Sure, let me know if you need something.
Regards.

**Comment by edvin** [comment]
Absolutely, thanks :)

**Comment by edvin** [comment]
I landed on the UIProvider, almost like the one I pasted here:

https://www.youtube.com/watch?v=-6PlFVUgntU

I realise that it might be a bit cumbersome to inject the UI into the launcher, but it should just be a matter of copying the lines from the sample project into your build :)

**Comment by pablovilas** [comment]
Great news!!, I'll try it tomorrow. Thanks!. 👏 👏

**Comment by edvin** [comment]
Cool, let me know how it goes :)

**Comment by pablovilas** [comment]
I let you know! :). It's possible to create a new github release? so the maven release will match.
Again, Thanks.

**Comment by edvin** [comment]
I totally forgot, thanks for reminding me. I drafted the release now.

**Comment by pablovilas** [comment]
Thanks!!! :)
