### ISSUE TITLE
JAXB unmarshal throws exception

### ISSUE THREAD

**Issue by mike-robinson** [edvin/fxlauncher#148]
I have run into an unusual problem that maybe you have seen. I use fxlauncher to update an application used by a small number of people (50) at different companies. They use a mixture of Mac OS and Windows 10. 49 of the users use the updater with no problems. However 1 user (Mac OS version 10.13.6) generates an exception in the syncManifest method of the AbstractLauncher at this line.

`manifest = JAXB.unmarshal(embeddedManifest, FXManifest.class);`

Right now I do not know what the exception is but I can confirm that the embedded manifest path is found properly.

Java 1.8.192 is the version embedded with the app. I did check the directories for the app and cache on the user's machine to insure permissions and owner/group were proper and they were. I also looked at the contents of the app on the user's machine and it all appeared normal.

I only post this to see if you or any other developers have run into an issue like this?

**Comment by edvin** [comment]
We'd have to see the exception to figure this out :)

**Comment by mike-robinson** [comment]
I'll get the exception when they come back to work on Monday. Will post
then. Thanks.

**Comment by mike-robinson** [comment]
Still could not see the exception while trying to catch a DataBindingException. It's a moot point now as the customer felt the user account on OS X was corrupted in some way. They created a new user account and the app ran fine under that account. It would have been nice to see the cause of the problem but right now I'm just content with moving on.
