### ISSUE TITLE
Can I pass JVM args to the application?

### ISSUE THREAD

**Issue by Taximan** [edvin/fxlauncher#153]
I would like to use G1GC for my application.  Can this be done with a non native launcher? I tried a line like this in my gradle (kts)

```kotlin
fxlauncher {
  applicationParameters = "-XX:+UseG1GC"
}
```

but sadly that didn't work.

**Comment by edvin** [comment]
Yes, since javapackager supports the `jvmOptions=option` parameter, you can configure that in the `javapackagerOptions` section :)

**Comment by serjant192** [comment]
How to add this arguments for virtual keyboard:
-Dcom.sun.javafx.isEmbedded=true
-Dcom.sun.javafx.touch=true
-Dcom.sun.javafx.virtualKeyboard=javafx

`fxlauncher {
    ...
    javapackagerOptions = ['-Dcom.sun.javafx.isEmbedded=true',  '-Dcom.sun.javafx.touch=true', '-Dcom.sun.javafx.virtualKeyboard=javafx']
}
`
I tried with javapackagerOptions, but it doesn't work.

**Comment by edvin** [comment]
Have a look in the documentation for javapackager: https://docs.oracle.com/javase/8/docs/technotes/tools/unix/javapackager.html

jvmOptions=option

Option to be passed to the JVM when the application is run. Any option that is valid for the java command can be used. To pass more than one option, use multiple instances of the -B option, as shown in the following example:

```
    -BjvmOptions=-Xmx128m -BjvmOptions=-Xms128m
```

That should do it :)

**Comment by serjant192** [comment]
Thank you for your prompt reply. You saved me a lot of time.

**Comment by edvin** [comment]
My pleasure :)

**Comment by 849996461** [comment]
thank you very much
