### ISSUE TITLE
Cross-platform launchers

### ISSUE THREAD

**Issue by MGlolenstine** [edvin/fxlauncher#164]
This might be a feature I've overlooked, but as far as I can see, there's no way to compile fxlauncher for Windows and MacOS on Linux. I know I have the .jar launcher, but I'd prefer having native launchers for both other OS without having to have them at hand.

**Comment by edvin** [comment]
You need to compile the installer once on each platform, but after that you can push updates without ever having to recompile the installer, so it’s not much of an issue IMO.

**Comment by MGlolenstine** [comment]
I know what you mean, but I don't really have access to any other systems. Does there really not exist any way to cross-compile?

**Comment by edvin** [comment]
You can subscribe to an online os as a service if you really don’t know anyone running other os’s :) We are using javapackager and os specific installer tools, so there is no way around, but I doubt you’ll really have a hard time getting 5 minutes access to a win and a Mac system :)

**Comment by MGlolenstine** [comment]
In our country there's really no easy access to MacOSX, but I can get Windows... But that sucks... If only there was a way to cross-compile.

**Comment by edvin** [comment]
I can compile the Mac binary for you if you want :)

**Comment by MGlolenstine** [comment]
That would be nice, thanks <3

**Comment by MGlolenstine** [comment]
@edvin What would you need for Mac compilation? I could provide you whole project, but I think that you need only the fxlauncher config(the properties in maven and main class)... right?

**Comment by edvin** [comment]
I'd need the whole project, since the initial installer will contain a compiled version of the current state of the app as well :)

**Comment by MGlolenstine** [comment]
Oh, sure. My project isn't hosted on GitHub and it's kinda private, so where can I send it to?

**Comment by edvin** [comment]
You can email it (or a download link) to me, es@syse.no :)

**Comment by MGlolenstine** [comment]
I'll do that later today
