### ISSUE TITLE
how to make fxlauncher without applicationUrl or localtion url

### ISSUE THREAD

**Issue by amasahara** [edvin/fxlauncher#169]
i try make demo with fxlauncher and i don't want online url so how can make fxlauncher without applicationUrl or any way without internet.
Thanks for watching

**Comment by edvin** [comment]
That’s not what it’s made for, but you might be able to give it a file://  URL. Alternatively, just use javapackager directly.

**Comment by amasahara** [comment]
thanks

**Comment by DHosseiny** [comment]
Can you explain this. I don't know what is javapackager. thanks

**Comment by edvin** [comment]
The docs says it all :)

https://docs.oracle.com/javase/8/docs/technotes/guides/deploy/packager.html
