### ISSUE TITLE
gradle plugin doesn't generate and include project jar

### ISSUE THREAD

**Issue by frosch95** [edvin/fxlauncher#17]
Hi,

I tried to get the gradle plugin work with my project, but it seems that the project jar isn't build and included. Only the dependencies are so I always get a ClassNotFoundException.

My gradle build file can be found here: https://github.com/frosch95/SmartCSV.fx/blob/fxlauncher/build.gradle

Thanks for your help.

Best regards,
Andi

**Comment by edvin** [comment]
Hi Andreas,

Thanks for reporting this. I can confirm that I see the same thing, and I'll look into this ASAP. I'm having a bit of a weird week with little computer time, so it might take me some days before I get back to you.

**Comment by edvin** [comment]
I found what I did wrong and published version `1.0.11.1`, it should be in Maven Central within the hour. Will you try it out and tell me how it went?

**Comment by frosch95** [comment]
Thx for the fast response. Could it be that the version number of fxlauncher and the gradle plugin has to be in sync?
I get the following error:

Could not find no.tornado:fxlauncher:1.0.11.1.
Searched in the following locations:
    https://repo1.maven.org/maven2/no/tornado/fxlauncher/1.0.11.1/fxlauncher-1.0.11.1.pom
    https://repo1.maven.org/maven2/no/tornado/fxlauncher/1.0.11.1/fxlauncher-1.0.11.1.jar
    https://jcenter.bintray.com/no/tornado/fxlauncher/1.0.11.1/fxlauncher-1.0.11.1.pom
    https://jcenter.bintray.com/no/tornado/fxlauncher/1.0.11.1/fxlauncher-1.0.11.1.jar

**Comment by edvin** [comment]
I'm so sorry, I made another stupid mistake and updated the fxlauncher dependency version as well. Gradle is very new to me :) I'm pushing 1.0.11.2 to Maven Central now. This version will be looking for fxlauncher 1.0.11.

Give it an hour and try again, OK?

**Comment by frosch95** [comment]
Excellent! The application jar is in the fxlauncher directory and the ClassNotFoundException is gone.
I have some other issues, I will post separately :-)

Thanks for your fast help!

**Comment by edvin** [comment]
Tthank you! You're probably the first user of the Gradle plugin, so anything you can contribute to make this more (or at all) useful is greatly appreciated.
