### ISSUE TITLE
Wix Custom template support

### ISSUE THREAD

**Issue by jaks80** [edvin/fxlauncher#182]
Dear @edvin, How do I configure custom wix (.wxs) template using fxlauncher. Wix template is in project directory. My application needs an MSI installer which starts automatically after installation. Default behavior of MSI is not to launch application after installation.

**Comment by edvin** [comment]
I'm sorry, I have no idea. FXLauncher is just calling javapackager, so whatever you can do with javapackager can be done with FXLauncher.

**Comment by jaks80** [comment]
Thanks a lot @edvin for quick reply.

**Comment by edvin** [comment]
Sorry I couldn't be of more help :)

**Comment by jaks80** [comment]
Thats fine Edvin. You are already very helpful.
