### ISSUE TITLE
adding custom files to manifest

### ISSUE THREAD

**Issue by butterklopsi** [edvin/fxlauncher#22]
it would be cool to be able to manually add files to the manifest that would be updated during the regular allplication start

**Comment by edvin** [comment]
Absolutely, right now, all files ending in zip or war will be included, but I'll make this a configurable list so you can include arbitrary files in the build directory and have them included.

**Comment by edvin** [comment]
This feature is now available in 1.0.13-SNAPSHOT. Add `--include-extensions=png,jpg,gif` as the last parameter to CreateManifest to include images in the manifest.

Can you confirm that this works the way you need it to?

**Comment by edvin** [comment]
It seems to be working good, so I'll close this.

**Comment by butterklopsi** [comment]
looks like it works for what i need, but i think i would be easier to add single files from the specific file-path and/or  a complete folder by its path
(sorry my was conntected to another network the last hours, so i was not able to post tis)

**Comment by edvin** [comment]
I understand. This feature of supporting extra extensions was already almost there, but we could add a better way to include specific files down the line as well. I'm trying to focus on TornadoFX right now, but we will get this into the rewrite of FXLauncher down the line.
