### ISSUE TITLE
A way to update the build in jre

### ISSUE THREAD

**Issue by PatrickHaas** [edvin/fxlauncher#24]
Hey Edvin,
could you think of any way to make it possible updating the build in jre too?
Besides customizing the updater ui (which was mentioned in another issue) and passing in some jmv arguments, it's the one thing left on my list :)

**Comment by edvin** [comment]
Hi! No, unfortunately that is outside the reach of FXLauncher in it's current form. For version 2.0 this is definitely on the list, but I need to concentrate on TornadoFX 100% until we finish the book and wrap up the last of the features we have in the pipe line. After that I will finish the updater ui (I've done a lot of it already but got hit with a lot of new features in TornadoFX). Sorry this is taking so long :)
