### ISSUE TITLE
${app.cachedir} get created if you dont have an <app.cachedir> directive

### ISSUE THREAD

**Issue by ronsmits** [edvin/fxlauncher#27]
Allthough the app.cachedir is optional, if you dont have it the directory is created as ${app.cachedir}:

````
ron@frankenstein ~/src/keepassjava $ ls
${app.cacheDir}  keepassJava.iml  openkeepass  pom.xml  README.md  sequences  src  target  USERDIR
ron@frankenstein ~/src/keepassjava $ 
````

**Comment by edvin** [comment]
I suspect your build references this variable, while it is not declared. I suspect this is just an oversight in your pom.xml. Show it to me and we'll find out :)

**Comment by edvin** [comment]
I will update the documentation to mention that if you uncomment the app.cacheDir reference, you must also remove it from the create-manifest step.
