### ISSUE TITLE
Gradle Plugin: SCP + Windows

### ISSUE THREAD

**Issue by dafe** [edvin/fxlauncher#29]
I'm bumping into an issue running the deployApp task in Gradle from my Windows dev box

> What went wrong:
> Execution failed for task ':deployApp'.
> java.io.IOException: Cannot run program "scp": CreateProcess error=2, The system cannot find the file specified

I've grabbed Putty's pscp, renamed it to scp and have it on my Path. I can manually scp the files from command line, but unsure why Java can't see the binary.

Anyone had any luck with this build task in Windows?

**Comment by dafe** [comment]
Looks like I didn't do enough initial troubleshooting, appears to be working fine now, java is able to locate and launch the executable just fine. 

Side note to anyone they might be trying to use pscp: There was another slight issue where pscp wants to connect using a putty key, so the build script was failing when trying to use my openssh key. I got around this by creating a separate putty key and created a saved session in putty itself using the new key, then it was a case of replacing the host with the name of the saved session eg.

instead of
> deployTarget 'w48839@fxldemo.tornado.no:fxldemo'

I've used
>deployTarget 'nameofputtysavedsession@fxldemo.tornado.no:fxldemo'

Build script runs successfully after this change, and I can see a successful connection/auth on the server end as well.

The only issue I'm left with now is that the files themselves are not actually uploaded. I will assume this is due to minor differences between *nix scp and pscp usage. For now I'm just falling back to a manual upload and will look at automating it later.

Going to close this issue as the original problem is now resolved.

**Comment by edvin** [comment]
Thanks for all the details, this will be helpful to others down the line for sure :)

**Comment by estebantcs** [comment]
Yes i can deploy the app. 
But i have another problem. when the the app opens WinSCP to save the files in host WinSCP tries to connect to "C" server i dont know why. i have a Apache server running local for host the files and a Fillezille Server running to transfer the files . i dont know if this the best approach. can you help  me?
