### ISSUE TITLE
Be able to pass remote URL on command line

### ISSUE THREAD

**Issue by countfloyd** [edvin/fxlauncher#3]
It would be really nice if you could pass the URL of the remote app.xml to the Launcher. This would be much easier than trying to replace the app.xml in the fxlauncher.jar file.

**Comment by countfloyd** [comment]
Also, of course you'd have to remove this argument from the ones passed to the application that you're launching.

**Comment by edvin** [comment]
This is actually how it used to work before the embedded manifest support was introdused :) Sure, I'll put it back in, slightly modified. I'm away this weekend, will get to it early next week.

**Comment by countfloyd** [comment]
That would be great! Thanks.

**Comment by edvin** [comment]
This feature is now available in FXLauncher 1.0.9, which should be in Maven Central within the hour. Usage:

```bash
java -jar fxlauncher.jar --app=http://remote/location/app.xml
```

Please let me know how it works out for you!

**Comment by countfloyd** [comment]
OK, will do. Thanks for the fast turnaround.

**Comment by edvin** [comment]
My pleasure. I'll close the issue now, feel free to open it again if needed.

**Comment by countfloyd** [comment]
This works great now, thank you. One little thing I noticed is that if the url in the app.xml doesn't end with /, it doesn't work. Perhaps I'll file an issue for this.

**Comment by edvin** [comment]
Great, thanks :)
