### ISSUE TITLE
Gradle plugin: Local JAR dependencies fail to copy

### ISSUE THREAD

**Issue by dafe** [edvin/fxlauncher#30]
When running copyAppDependencies from the Gradle plugin, I'm bumping into an issue where the local jar dependencies I've defined are not being copied to the fxlauncher folder, and have no entry in app.xml

So in my build.gradle I'll use either 'fileTree' or 'files' to compile my local dependencies (I've tried testing both)

```
dependencies {
        compile fileTree(dir: 'lib', include: '*.jar')
        compile files('lib/example1.jar', 'lib/example2.jar')
}
```

I'm fairly new to Gradle so not sure if I'm missing something obvious.

Cheers.

**Comment by edvin** [comment]
Hi! I'm fairly new to gradle myself and had help creating the plugin, but I suspect the plugin will only copy dependencies defined in a repo, not adhoc stuff based on files. To make this work with the current version of the plugin you can install these files into your local maven repo and refer to them with maven coordinates (remember to add mavenLocal()). I'll try to figure out how to deal with adhoc files ASAP, but unfortunately I'm bogged down with work at the moment, so this could take a while. I hope you can use the workaround described above in the meantime.

**Comment by rogeriomq** [comment]
I use small apps the task jar fat to generate just one jar with embedded dependencies. Modifying the pluggin fxlauncher to catch only the jar generated by fatjar?

**Comment by edvin** [comment]
For FXLauncher deployment I see no upside to this. It means that even if you just change one dependency your clients would have to download all dependencies again.

**Comment by dafe** [comment]
I followed your suggestion with the local maven repo, so it's copying across as expected now, thanks for pointing me in the right direction!

**Comment by edvin** [comment]
Great to hear :) Can you live with this for now, so we close the issue?

**Comment by dafe** [comment]
Yep, solution works well. Closing :)
