### ISSUE TITLE
Bug: Basic auth is not working for domain subdirectories?

### ISSUE THREAD

**Issue by humpfle** [edvin/fxlauncher#32]
Basic auth is not working properly for subdirectories, i.e. if the files are stored in: **host.de/subdirectory**

Maven App URL configuration;

**<app.url>http://user:password@host.de/subdirectory</app.url>**

=> With this configuration, an exception occurs: FileNotFoundException: http://user:password@host.de/someJar.jar

It seems that the **subdirectory** is ignored.

I´ve found out that there is a workaround by extending the maven <app.url> configuration

<app.url>http://user:password@host.de/subdirectory/**any_string_workaround**</app.url>

=> Now the path host.de/subdirectory seems to be resolved correctly

**Comment by edvin** [comment]
Can you try to simply add a trailing / to the URL?

http://user:password@host.de/subdirectory/

**Comment by humpfle** [comment]
ok, i´ve found the solution:

the configuration must be http://user:password@host.de/subdirectory**/**
instead of http://user:password@host.de/subdirectory

sorry for any circumstances. 

(now i got server 401 although the creditials works in the browser, but thats another issue)

**Comment by edvin** [comment]
What version of FXLauncher are you using?

**Comment by edvin** [comment]
And can you possibly send me the URL with a working username and password so I can try it?

**Comment by humpfle** [comment]
I´m using version 1.0.13

**Comment by edvin** [comment]
Great. I have found the error and I'm working on it now :)

**Comment by humpfle** [comment]
ok, i guess you don´t need the user/pass anymore?!

**Comment by edvin** [comment]
Probably not :) Hang on!

**Comment by edvin** [comment]
I have committed a fix for this is 1.0.14-SNAPSHOT. Do you know how to build from source and try this?

**Comment by edvin** [comment]
Attached is version 1.0.14-SNAPSHOT with the fix. You can install it into your local Maven repo like this:

mvn install:install-file -Dfile=fxlauncher-1.0.14-SNAPSHOT -Dversoin=1.0.14-SNAPSHOT -Dpackaging=jar -DgroupId=no.tornado -DartifactId=fxlauncher

After that you should be able to update to version 10.0.14-SNAPSHOT in your project, do a clean build and try it. Let me know how it goes, OK? :)

[fxlauncher-1.0.14-SNAPSHOT.zip](https://github.com/edvin/fxlauncher/files/551860/fxlauncher-1.0.14-SNAPSHOT.zip)

**Comment by humpfle** [comment]
yes i can check it out and build a snapshot, thanks

**Comment by edvin** [comment]
Perfect, thank you! I need to get to bed now. If it works I'll release 1.0.14 tomorrow after doing some more quality tests, it's getting late here in Norway :)

**Comment by humpfle** [comment]
the snapshot version 1.0.14 is working great! thanks and good night

**Comment by edvin** [comment]
Version 1.0.14 is now in Maven Central. Thank you for the bug report and your patience.
