### ISSUE TITLE
javapacker not found ?

### ISSUE THREAD

**Issue by ianjohnspain** [edvin/fxlauncher#33]
Hi,

I am using tornadofx and built a small helloworld app and I know I wish to create a native installer (I am on Linux MINT Kde), I am using gradle. So I found fxlauncher that seems to do more than I originally wanted. I tried running the generateNativeInstaller but i get the following errors

> :embedApplicationManifest
> :generateNativeInstaller FAILED
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':generateNativeInstaller'.
> > java.io.IOException: Cannot run program "javapackager": error=2, No such file or directory
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
> 
> BUILD FAILED
> 
> Total time: 12.873 secs
> error=2, No such file or directory
> 2:53:53 AM: External task execution finished 'generateNativeInstaller'.

I did the following to my gradle file, placing it here for transparency.

```
buildscript {
    ext.kotlin_version = '1.0.4'

    repositories {
        mavenLocal()
        mavenCentral()
    }
    dependencies {
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'no.tornado:fxlauncher-gradle-plugin:1.0.14'
    }
}

apply plugin: "kotlin"
apply plugin: 'no.tornado.fxlauncher'


fxlauncher {
    applicationVendor 'My Company'
    applicationUrl 'http://soemthing/'
    applicationMainClass 'com.example.demo.app.MyApp'
    acceptDowngrade false
    deployTarget 'w48839@fxldemo.tornado.no:fxldemo'
}

repositories {
    mavenLocal()
    mavenCentral()
}

apply plugin: 'application'

dependencies {
    compile 'no.tornado:tornadofx:1.5.7'
    testCompile 'junit:junit:4.12'
}

jar {
    manifest {
        attributes(
                'Class-Path': configurations.compile.collect { it.getName() }.join(' '),
                'Main-Class': 'com.example.demo.app.MyApp'
        )
    }
    from configurations.compile.collect { entry -> zipTree(entry) }
}
```

Can anyone help, I must admit when it comes to java / gradle I wouldn't consider myself a complete expert :-)  Although I love Kotlin!

**Comment by ianjohnspain** [comment]
I suppose what I am trying to achieve is a native installer (for linux) using a self contained package i.e. having the version of java/kotlin/fx come along for the ride so that the end user doesn't need to install anything separately.

More info here http://docs.oracle.com/javafx/2/deployment/self-contained-packaging.htm

**Comment by edvin** [comment]
Hi! This simply means that you don't have javapackager in your path. Javapackager is a part of the Oracle JDK, so make sure you install it and add $JAVA_HOME/bin to your path. That will happen automatically if you install the official Oracle JDK. There should be a ppa you can add to your installation to get this working. Try something like this:

http://tecadmin.net/install-oracle-java-8-jdk-8-ubuntu-via-ppa/#

**Comment by ianjohnspain** [comment]
Thanks edvin for the reply. I actually installed JAVA 1.8 jdk and added it to my path. I have also done the following in a terminal, it seems everything is available or maybe I am missing something ?

```
ian@ian-mint ~/IdeaProjects/NewFxDemo> which java                                      04:46:39
/usr/lib/jvm/jdk1.8.0_111/bin/java
ian@ian-mint ~/IdeaProjects/NewFxDemo> java -version                                   04:46:42
java version "1.8.0_111"
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)
ian@ian-mint ~/IdeaProjects/NewFxDemo> which javapackager                              04:46:49
/usr/lib/jvm/jdk1.8.0_111/bin/javapackager
ian@ian-mint ~/IdeaProjects/NewFxDemo>                                                 04:47:02
```

and heres my path

```
ian@ian-mint ~/IdeaProjects/NewFxDemo> echo $PATH                                      04:48:02
/usr/lib/jvm/jdk1.8.0_111/bin /usr/local/sbin /usr/local/bin /usr/sbin /usr/bin /sbin /bin /usr/games /usr/local/games
```

Do you see anything a miss ?

**Comment by edvin** [comment]
Weird. Are you running the build from the same shell you used here? If you're running from the IDE you might have a different path there perhaps? If not, try also to comment out that jar-step, that's the only thing that differs from the fxldemo-gradle example AFAIK. If that doesn't work I'll try to set up a desktop with linux mint and test directly. Let me know!

**Comment by edvin** [comment]
Closing this due to no reply.
