### ISSUE TITLE
Future plans?

### ISSUE THREAD

**Issue by ChrisLMerrill** [edvin/fxlauncher#37]
Curious to know if you have a plan for future enhancements for this project? Or do you consider it "done"?

There are a couple of features that come immediately to mind when I consider using this in my project:
1) Support for updating to specific versions or downgrading to specific versions. Even in the best-run projects. there are bugs or incompatibilities that take a while to fix. Allowing my users to downgrade to a specific version until a bug could be fixed might be very valuable to them. 
2) Support multiple update channels. E.g. Allow users to switch to (or from) a beta channel to get the latest goodies or the most stable release.
3) Delay updating and expose APIs to the target software for controlling updates. So instead of updating at startup, it would simply check for updates and then allow my software to notify the user that updates are available and ask them if/when they would like to update at the next startup.

Thanks!
Chris

**Comment by edvin** [comment]
Hi Chris,

My plan is to reboot the project once Java 9 is nearing completion. I think the current version is stable and working quite well, but I would like to rewrite everything based on what I know now and make it much more extensible + introduce a plugin architechture to make it easier to contribute new functionality.

There are a lot of cool things we can do in the context of Java 9 / Jigsaw, but as you point out there are also a lot of things we could do that has nothing to do with Java 9. I particularly like your idea about update channels and delayed updates, rollback to specific versions etc. These are must haves for a reboot of this project.

I'm also thinking about creating native stubs for each platform to make it much nicer to create native installers, skipping over the need for javapackager altogether. This will be an optional feature though, and javapackager will still be supported, but I think we can achieve much better integration by going this route.

Another idea I have is for an app store like functionality where you can browse and install fxlauncher enabled software, possibly categorized and maybe even with the option to sell licenses etc.

If you are up for it, you can submit a PR for a document describing wanted features for the FXLauncher 9 reboot, so we can start gathering ideas for the next version. In the mean time I'll continue to add smaller features to the current branch upon request.

**Comment by ChrisLMerrill** [comment]
Thanks for the response!

The other project I looked at for installers was https://github.com/FibreFoX/javafx-gradle-plugin . I felt like it had much more customization for installers...though I don't know enough to feel confident about that statement. I chose your project because, for now, it was simpler and I think my users will REALLY appreciate the auto-update. But if you are considering a complete re-write, maybe you should consider focusing on the auto-update part and working with that project to handle the installer part. Just an idea...I don't know if that is even feasible.

As for the things I want - 3 suggestions I made in this issue cover everything I envision needing. If you'd like me to elaborate on those, I can do that. As for the app-store and licensing ideas, I don't think that is something I would make use of.

Thanks for this project...saved me a lot of work!

**Comment by edvin** [comment]
Thanks for the input. I'm excited to begin the reboot, and I agree that the update prosess is what should receive the most love. There are a lot of things we can improve for sure.
