### ISSUE TITLE
Failure modes and logging

### ISSUE THREAD

**Issue by ChrisLMerrill** [edvin/fxlauncher#38]
I'm having trouble with the update step when I startup my app. I didn't find any debugging information on the readme....so not sure how to diagnose the problem. Note that the very first time I ran the installer, it updated fine. Since then, the results have not been as good. 

Problem 1:  My app has 87 jars (most are 3rd-party). When it gets to one of MY jars, it stops updating and tries to run the app. This results in a ClassNotFound error instead of reporting the real problem (which is that the download failed for some reason). I don't understand what is different about my jars. 

Problem 2: When I copy MY jars in, it hangs on some of the other 3rd party jars, but in this case, the update hangs. The progress bar goes back and forth (instead of filling in). If I manually copy in the remaining jars from the fxlauncher, then the app starts.

I can't tell if this is some odd network problem, a checksum problem, or something else. Is there a way to turn on some verbose debugging?

Also, how is the checksum in the manifest computed? I tried computing using md5sum and cksum - neither matches the value I see in the manifest.

Thanks!
Chris

**Comment by edvin** [comment]
That's weird. If there were any network errors during the update process you should see a stack trace on the console. Did you run the app with `java -jar fxlauncher.jar`?

**Comment by edvin** [comment]
The checksum used is **Adler32**. It is implemented like this:

```java
    private static long checksum(Path path) throws IOException {
        try (InputStream input = Files.newInputStream(path)) {
            Adler32 checksum = new Adler32();
            byte[] buf = new byte[16384];

            int read;
            while ((read = input.read(buf)) > -1)
                checksum.update(buf, 0, read);

            return checksum.getValue();
        }
    }
```

**Comment by ChrisLMerrill** [comment]
Sorry, I should have mentioned that I'm using the native windows launcher. Didn't realize the output was going to the console...that explains why couldn't find a log file :)

I'll add an enhancement request for writing errors to a log file when using native launchers.
