### ISSUE TITLE
Enhancement: native installers should log update/startup errors to a log file

### ISSUE THREAD

**Issue by ChrisLMerrill** [edvin/fxlauncher#39]
When running from a native installer, the end-user won't see anything logged to stdout. Requiring users to run the program from the command-line to capture the output is not a good end-user experience. It would be great if the launcher would redirect all of its output to a log file that can be easily located by the end-user...perhaps even showing giving them the opportunity to view it or save it to the desktop when an error occurs.

**Comment by edvin** [comment]
Sorry for the late reply. I'm swamped with writing documentation for TornadoFX and stuff at work, so I have to put this on the back burner. I'll get to it as soon as possible.

**Comment by terjedahl** [comment]
Actually, I would go the opposite way.  Consider pulling native installers out of the project - and in stead have it as a separate project, if desired.  Perhaps I should suggest this in e separate issue?

**Comment by edvin** [comment]
That's an interesting thought, Terje. I will for sure consider this for the reboot/2.0.

**Comment by ronsmits** [comment]
@ChrisLMerrill can you check if the changes fxlauncher where it always logs to a known file satisfies your request?

**Comment by ronsmits** [comment]
As this has been open for more then a month without response, closing it.
