### ISSUE TITLE
Download the right version of JRE

### ISSUE THREAD

**Issue by romikk** [edvin/fxlauncher#4]
Quite often the end user doesn't have JRE supported by the app, e.g. user has 1.6 and we need a 1.8.
Therefore it would be handy if FXLauncher could download packaged JRE along with the application jars. This would make user experience even more seamless without asking users to update their Java or investigating why application uses the wrong version of JRE (if multiple are installed) or why JRE installation is broken. Unfortunately this happens quite often.

**Comment by edvin** [comment]
If you need to control the JRE version of the client, it is a good practice to wrap the launcher with javapackager as it's done in the Maven and Gradle examples. Is there a reason why this isn't a good fit for you? While it would be possible to download the JRE and relaunch the app, that would drastically change the way FXLaucher works, and to me it seems like your use case is already covered by javapackager, or alternatively Advanced Installer or some other similar tool. Is there a reason why this isn't a good match for you?

It would be quite easy to check/require a minimal JRE version, and possibly warn/redirect the user to JRE download if that would help your use case.
