### ISSUE TITLE
Synchronisation problem

### ISSUE THREAD

**Issue by SylvainAssemat** [edvin/fxlauncher#43]
Hi Edvin

Thanks for your work 

I have a little question 

When i try to run : 

**java -jar target/app/fxlauncher.jar**
janv. 28, 2017 5:12:19 PM fxlauncher.Launcher lambda$start$0
INFOS: Using cache dir ${app.cacheDir}
janv. 28, 2017 5:12:19 PM fxlauncher.Launcher lambda$start$0
AVERTISSEMENT: Error during File Synchronization phase
java.io.FileNotFoundException: http://www.myfowo.com/rondoclient-1.0.0.jar
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLCo
nnection.java:1872)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLCon
nection.java:1474)
        at fxlauncher.Launcher.syncFiles(Launcher.java:159)
        at fxlauncher.Launcher.lambda$start$0(Launcher.java:78)
        at java.lang.Thread.run(Thread.java:745)

I should miss something but can't find the fix

Could you help me ?

Thanks

**Comment by edvin** [comment]
Hi :) It looks like you fixed your problem. The rondoclient-1.0.0.jar was not uploaded correctly it seems :) Let me know if you have any more issues.

**Comment by SylvainAssemat** [comment]
Yes i solve it juste a minute after writting the issue
I delete the .jar so it s no longer available right now.

I just missing the put a "/" at the end of the app-url parameter

\o/

Sorry for the inconvenience

**Comment by edvin** [comment]
Ah, right :) I've seen many people having that issue with the missing /. I'll see if I can make this optional for the next release.
