### ISSUE TITLE
FxlDemo-2.0.exe  error

### ISSUE THREAD

**Issue by Rhain** [edvin/fxlauncher#5]
when I run the FxlDemo-2.0.exe ,after it finished. I got this error :
![image](https://cloud.githubusercontent.com/assets/1488036/13770589/21d1838a-eac3-11e5-82fb-02803d3698e7.png)  .so I need put app.xml in some folder?

**Comment by edvin** [comment]
Hi Rhain,

I believe the installer might have been corrupted - can you download it again and try once more?
