### ISSUE TITLE
human-readable timestamp

### ISSUE THREAD

**Issue by terjedahl** [edvin/fxlauncher#51]
Alter manifest.ts to use a more human-readable timestamp.
Alt 1: a la Maven: Integer: yyyymmddhhmmss
Alt 2: java.sql.Timestamp (ISO-format): String: "yyyy-mm-dd hh:mm:ss"
Question: Is millisecond resolution needed/useful?

**Comment by edvin** [comment]
This would break existing clients trying to download the manifest, so I don't think it's worth it.

**Comment by terjedahl** [comment]
OK.  Good point.
