### ISSUE TITLE
USERLIB and Windows 

### ISSUE THREAD

**Issue by imario42** [edvin/fxlauncher#52]
Hi!

I wonder if the Windows path construction in FXManifest for the USERLIB is fully correct.
Shouldn't there be a Local/LocalLow or Roaming in the path?
I'd prefer "Local" for now.

`
               case win:

                    replacement = Paths.get(System.getProperty("user.home"))
                            .resolve("AppData")
                            .resolve("Local")
                            .resolve(cacheDir.substring(8))
                            .toString();
                    break;
`

What do you think?

**Comment by edvin** [comment]
I think you're correct :) I'll change it right away.
