### ISSUE TITLE
Classloader woes

### ISSUE THREAD

**Issue by imario42** [edvin/fxlauncher#53]
Hi!

I had hard times to get fxlauncher working with my app which uses custom URLStreamHandler which could not be loaded by my app if started using fxlauncher.

It came down to the java.net.URL class which uses Class.forName() which uses the classloader of the callee (which is the URL class). But this classloader is not aware of the URLClassLoader created by fxlauncher and thus is not able to instantiate my URLStreamHandler.

I was able to workaround that by setting my own URLStreamHandlerFactory. But, well, it looks a bit of a hack (see below), because I have to handle a recursive case where (after setting up the URLStreamHandlerFactory) java has to load all the handlers again, even the builtin for file/jar/http/etc ...
And then, who knows which other java classes are using Class.forName .

Long story short, I think we need to create a system class loader and set that up using the startup parameter (-Djava.system.class.loader=myClassLoader) which allows us to add the additional classpath entries directly to this classloader instead of creating a new one.

Basically a URLClassLoader where we unprotect addURL()

What do you think?

`

       // old solution: System.setProperty("java.protocol.handler.pkgs", "my.base.class");

        URL.setURLStreamHandlerFactory(protocol ->
        {
            if (recursiveUrlHandler)
            {
                return null;
            }
            try
            {
                recursiveUrlHandler = true;
                URLStreamHandler handler = (URLStreamHandler) Utils.forName("my.base.class." + protocol + ".Handler").newInstance();
                return handler;
            }
            catch (Throwable e)
            {
                return null;
            }
            finally
            {
                recursiveUrlHandler = false;
            }
        });

`

**Comment by edvin** [comment]
Is this issue solved by your PR so we can close it? https://github.com/edvin/fxlauncher/pull/55

**Comment by ronsmits** [comment]
This should be fixed by the new ClassLoader mechanism that @imario42 made. Closing the ticket.
