### ISSUE TITLE
Headless mode

### ISSUE THREAD

**Issue by imario42** [edvin/fxlauncher#56]
I thought about using your fxlauncher not just for FX stuff, but also for plain java installations. e.g. running headless as windows service.
Having a headless mode of fxlauncher could also allow such a java service update itself.

In fact, I have it already running on my machine, but it requires some additional efforts to avoid code duplications.

I thought about refactoring Launcher into

* AbstractLauncher for common stuff
* extending Launcher from it for the current FX behavior
* extending a new HeadlessMainLauncher from AL. This launcher will run headless and will invoke the main method of the loaded application

Because this leads to a bigger pull request I wanted to ask if you are interested in such a thing at all - or is this out of scope of your library?

**Comment by edvin** [comment]
I've been thinking about headless mode myself, this would be a very welcome feature indeed! I think your approach seems reasonable, so please go ahead :)

**Comment by edvin** [comment]
I'll close this issue since the PR is already merged :)
