### ISSUE TITLE
Use a library instead of an installed scp to transfer the files to the server

### ISSUE THREAD

**Issue by ronsmits** [edvin/fxlauncher#59]

**Comment by edvin** [comment]
We should consider JSCH: http://www.jcraft.com/jsch/

**Comment by ronsmits** [comment]
I was thinking of https://github.com/hierynomus/sshj

**Comment by edvin** [comment]
That looks good, I'd be fine with either one. The most important thing is that it can pick up keys from user_home.

**Comment by ronsmits** [comment]
Closing this, as it is now done in the maven plugin
