### ISSUE TITLE
How does one get access to this from their application? Library function: Launcher.checkForUpdate().

### ISSUE THREAD

**Issue by gcstang** [edvin/fxlauncher#64]
I have a gradle application and would like to call this from my own application is there a jar dep I need to add to my configuration?

**Comment by edvin** [comment]
You need the FXLauncher jar as a dependency:

```gradle
compile 'no.tornado:fxlauncher-gradle-plugin:1.0.15'
```

Should do the trick. Does that work for you?

**Comment by gcstang** [comment]
Are these the same?

classpath 'no.tornado:fxlauncher-gradle-plugin:1.0.15'

compile 'no.tornado:fxlauncher:1.0.16'

I tried with the gradle-plugin and it didn't work but change to the 16 version name and it worked.

**Comment by gcstang** [comment]
I came back to the site because I have an app and pushed the latest to my server for the updates to be pulled down with deployApp but when I open my application the update flies by and the latest isn't pulled down.  Is there a log or something I can look at to see what is going wrong and why the latest isn't pulled?  I'm on a Mac and and not using a cacheDir so it downloads where it's run from instead.  The update works the first time but not afterwards.

**Comment by edvin** [comment]
Sorry, I gave you the wrong coordinates, but you figured it out. Updated my post above in case somebody comes across this later.

About the update issue, start with confirming that your site actually contains the updated files. Then try running `java -jar fxlauncher.jar` from the command line. The log should appear on your console.

**Comment by gcstang** [comment]
Ok, yeah I didn't realize that they're two separate projects until afterwards... will the gradle plugin be updated to have the new parameters in it?  As an example: stopOnUpdateErrors

I'd be happy to update the plugin but when I try to build it locally as a jar I see the error about missing a value: ossrhUsername and ossrhPassword.

I don't have a lot of maven experience but I've done a fair amount of work on gradle.

**Comment by gcstang** [comment]
It seems the update issue is possibly coming from the Apache HTTP server and it caching files by default.

**Comment by gcstang** [comment]
Maybe we can add some more output to the fxlauncher when run from the jar in the command line output?  For example the last date/time from the file it checks to ensure we're getting the latest that we think we pushed?

Also if I run the Launcher.checkForUpdate() from my IDE it seems fine but after packaging with deployApp the following error occurs.

`Exception in thread "AWT-EventQueue-0" java.lang.NoSuchMethodError: fxlauncher.Launcher.checkForUpdate()Lfxlauncher/FXManifest;
	at com.javafx.ui.application.Main.lambda$checkForUpdate$1(Main.java:214)
	at java.awt.MenuItem.processActionEvent(MenuItem.java:669)
	at java.awt.MenuItem.processEvent(MenuItem.java:628)
	at java.awt.MenuComponent.dispatchEventImpl(MenuComponent.java:355)
	at java.awt.MenuComponent.dispatchEvent(MenuComponent.java:343)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:761)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)`

**Comment by edvin** [comment]
We could easily output the timestamp from the manifest, but the file changed is not something that is necessarily exposed over http. Apache doesn't cache files by default, so unless you have some custom caching configured that can't be the reason you didn't see the latest version.

About the `NoSuchMethodError` - Could it be that your installer was not created with FXLauncher 1.0.16? Remember, FXLauncher itself is not updated through the manifest, so you might need to create a new native installer and push out to your clients for this feature to be available. We're going to cover launcher updates in version 2.0.

**Comment by edvin** [comment]
Oh, and I'll make sure to add `stopOnUpdateErrors` and friends to the plugin shortly :)

**Comment by gcstang** [comment]
Yes I was referring to the timestamp from the manifest, that would at least tell me if it's pulling the correct version.

I still haven't found the issue with it not updating after the initial pull.  Maybe instead of a URL via HTTP I can just try it with a different local directory.

**Comment by gcstang** [comment]
It looks like the gradle plugin is bringing in the versioni 1.0.15 of the no.tornado:fxlauncher as a dependency.

**Comment by edvin** [comment]
Ah, yes, the gradle plugin is not updated to 1.0.16. I will start working on the feature additions and release 1.0.16 shortly, probably tonight.

**Comment by gcstang** [comment]
Sounds good, thank you.

**Comment by gcstang** [comment]
Any updates?

**Comment by edvin** [comment]
Hi! The Gradle plugin version 1.0.16 was released on 22. of April. Sorry I never reported back here, I've been crazy busy lately. Does that release solve the issue for you?

**Comment by gcstang** [comment]
I don't see the additional stopOnUpdateErrors added to the new version.

**Comment by edvin** [comment]
I talked to @ronsmits who made this function and he tells me it's only intended to be used from the command line. If you see a need for configuring this in the manifest we could add it though.

**Comment by gcstang** [comment]
It would be nice to have this and if there are errors stop the update from occurring along with some sort of UI to show that it happened.

**Comment by edvin** [comment]
I agree, I see no reason why this option couldn't be saved to the manifest as well. I don't have time to add it myself right now, as I'm preparing for Java One among other things that need to have priority. Do you want to try to add it perhaps?

**Comment by gcstang** [comment]
I'd be happy to, I'll get to it as soon as I can (working on several other projects but I'll make some time).

**Comment by edvin** [comment]
Thank you, great to hear!
