### ISSUE TITLE
Icon of windows executable not change

### ISSUE THREAD

**Issue by arthurcvm** [edvin/fxlauncher#67]
I set in my pom.xml the icon of application:

`<execution>
                        <id>installer</id>
                        <phase>install</phase>
                        <goals>
                            <goal>exec</goal>
                        </goals>
                        <configuration>
                            <executable>javapackager</executable>

                            <arguments>
                                <argument>-deploy</argument>
                                <argument>-native</argument>
                                <argument>-outdir</argument>
                                <argument>${app.installerdir}</argument>
                                <argument>-outfile</argument>
                                <argument>${app.filename}</argument>
                                <argument>-srcdir</argument>
                                <argument>${app.dir}</argument>
                                <argument>-srcfiles</argument>
                                <argument>fxlauncher.jar</argument>
                                <argument>-appclass</argument>
                                <argument>fxlauncher.Launcher</argument>
                                <argument>-name</argument>
                                <argument>${project.name}</argument>
                                <argument>-title</argument>
                                <argument>${project.name}</argument>
                                <argument>-vendor</argument>
                                <argument>${app.vendor}</argument>
                                <argument>-Bicon=src/main/resources/favicon.ico</argument>
                                <argument>-BshortcutHint=true</argument>
                                <argument>-BmenuHint=true</argument>
                                <argument>-BappVersion=${app.version}</argument>
                                <argument>-Bidentifier=${project.groupId}.${project.artifactId}</argument>
                            </arguments>
                        </configuration>
                    </execution>`

In install is all ok, but in installer archive (.exe) the icon not change, look:

![2017-04-17 1](https://cloud.githubusercontent.com/assets/9640276/25078186/1d6ce424-2307-11e7-9e78-e6ce1a951db9.png)

![2017-04-17 2](https://cloud.githubusercontent.com/assets/9640276/25078190/28866fc4-2307-11e7-864f-24f1de74f9bf.png)

And in the launcher:

![2017-04-17 4](https://cloud.githubusercontent.com/assets/9640276/25078233/73f58fe4-2307-11e7-8e63-e248c01158e9.png)

**Comment by ronsmits** [comment]
The icon is a seperate thing, the startup error seems to be SCP and windows related
investigating

**Comment by arthurcvm** [comment]
The error of launcher is because I still don't configure de server. But about the icon, in javafx maven plugin I change icon in bundler options in pom.xml and solve this.

**Comment by edvin** [comment]
So you're all good? Can we close the issue?

**Comment by arthurcvm** [comment]
Not solve nothing, please close the issue.
