### ISSUE TITLE
Problems wit SCP

### ISSUE THREAD

**Issue by estebantcs** [edvin/fxlauncher#71]
Hi a very new to FxLauncher i trying to run the gradle sample app but every time i run deploy task i recive this error:

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':deployApp'.
> java.io.IOException: Cannot run program "scp": CreateProcess error=2, The system cannot find the file specified
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

Can u help me?

**Comment by edvin** [comment]
This means that you don't have scp installed :) It looks like you're on Windows, so you can try WinSCP. It needs to be in the path, so after you have installed it, double check that you can open a shell and write scp without issues.

https://winscp.net/eng/download.php

PS: We're working on a Maven plugin for FXLauncher which will include scp support in a library so you won't have to install it locally.

**Comment by estebantcs** [comment]
thanks

**Comment by edvin** [comment]
Did you get it working?

**Comment by estebantcs** [comment]
Yes i can deploy the app.
But i have another problem. when the the app opens WinSCP to save the files in host WinSCP tries to connect to "C" server i dont know why. i have a Apache server running local for host the files and a Fillezille Server running to transfer the files . i dont know if this the best approach. can you help me?

**Comment by edvin** [comment]
Maybe you'll be better off with a command line scp client. I usually install gitbash, which includes the scp binary.
