### ISSUE TITLE
How to run in headless mode with native installers?

### ISSUE THREAD

**Issue by bj03rnv0ss** [edvin/fxlauncher#73]
I have a Java FX Project building with Maven and use the FXLauncher to enable auto updating the application. Native installers are created using the javapackager deploy command. I realized everything as it is demonstrated in the demo maven project and everything works fine.

Now I want the FXLauncher to start in headless mode, because my application is running in the background. The user interface is only displayed in case the user calls it over the tray icon. According to the documentation FXLauncher can be started in headleass mode with the corresponding command on command line:

`java -classpath fxlauncher.jar fxlauncher.HeadlessMainLauncher`

If I am executing this command on comand line after installing the native bundle it works pretty fine. The problem I am struggeling with is that I can't figure out how to configure the javapackager to create an executable starting the fxlauncher with the fxlauncher.HeadlessLauncher. How can this be realized?

Thanks

**Comment by edvin** [comment]
It looks like this was an oversight in the initial implementation of the headless launcher support. Right now you would have to change the `Main-Class` parameter of `META-INF/MANIFEST.MF` to `fxlauncher.HeadlessMainLauncher` inside `fxlauncher.jar` before you deploy your app. You should be able to do that by issuing the following command after the create manifest step:

```shell
jar uef fxlauncher.HeadlessMainLauncher fxlauncher.jar
```

If you want to make this into an execution step it would probably look like:

```xml
<execution>
    <id>configure-headless-launcher</id>
    <phase>package</phase>
    <goals>
        <goal>exec</goal>
    </goals>
    <configuration>
        <executable>jar</executable>
        <workingDirectory>${app.dir}</workingDirectory>
        <arguments>
            <argument>uef</argument>
            <argument>fxlauncher.HeadlessMainLauncher</argument>
            <argument>fxlauncher.jar</argument>
        </arguments>
    </configuration>
</execution>
```

Put it in `pom.xml` after the `embed-manifest-in-launcher` step. We will make sure to support this directly in the upcoming Maven plugin at some point :) What do you think, @ronsmits?

Does that work for you?

**Comment by bj03rnv0ss** [comment]
That does the trick! Thank you very much.
