### ISSUE TITLE
Class not found exception

### ISSUE THREAD

**Issue by Koire** [edvin/fxlauncher#74]
I'm sorry, I think I'm stupid or something, I can't for the life of me figure out how to add this to a gradle javafx project.
I'm using aws gradle sync to upload, which is working, but none of the builds actually run, I always get 
java.lang.ClassNotFoundException: app.main.LavenderClient
My javaFX client "LavenderClient" runs correctly however.

**Comment by edvin** [comment]
You haven't given much info to work with, but maybe you could start by posting the resulting fxlauncher.jar?

**Comment by Koire** [comment]
Sure, I'm really sorry about that, I was busy working on making some POJOs from a decently large API.

I'm using this for the build.gradle:
`fxlauncher {
    applicationVendor 'KWC'
    applicationUrl 'https://s3-ap-northeast-1.amazonaws.com/kwc-lavender-app/builds/LavenderClient-0.1.0.jar'
    applicationMainClass 'app.main.LavenderClient'
    acceptDowngrade false
    deployTarget 'https://s3-ap-northeast-1.amazonaws.com/kwc-lavender-app/builds/LavenderClient-0.1.0.jar'
}
apply plugin: 'jp.classmethod.aws.s3'
task syncToS3(type: jp.classmethod.aws.gradle.s3.SyncTask) {
    bucketName 'kwc-lavender-app/builds'
    source file('build/fxlauncher')
}`

when I package my app using the javafx packager, it works perfectly, but with the fxlauncher I always get a not found exception

[fxlauncher.jar.zip](https://github.com/edvin/fxlauncher/files/967535/fxlauncher.jar.zip)

**Comment by edvin** [comment]
Thank you :) You have two problems:

1. The `applicationUrl` parameter. It is supposed to point to the http address where app.xml and the other app artifacts are deployed. You have pointed it to the jar instead. 

2. `deployTarget` should point to an scp endpoint: `user@host:path`. This endpoint should correspond to the applicationUrl when fetched over http. You also need to have scp installed, and you must make sure to have authenticated against `user@host` so deploy can work unattended. If you can't make this happen, you can upload your artifacts so they are visible at `applicationUrl` manually.

Does that help?

**Comment by Koire** [comment]
I don't know how you can scp to the s3 bucket...

**Comment by edvin** [comment]
Since you use aws gradle sync to upload, the value of deployTarget doesn't matter. Just correct applicationUrl :)

**Comment by Koire** [comment]
Thank you so much, that worked, but I had to make the folder public, is there a way to add a key or something to keep it private?

**Comment by edvin** [comment]
You can use Basic Auth by supplying username/password in the url on the form `http://user:pass@host/path`, or you can just add an UUID or something unguessable as part of the path to the app and make sure the previous directory is not browsable.

Ultimately though you must make sure that the application resources are protected with a strong authentication scheme. For most applications, public access to the libraries themselves should not be problematic.

**Comment by Koire** [comment]
Thanks, looking into that now.
I fixed the debian install by chown-ing it to the user, however, when I run it via command line I get this error:
java.io.IOException: Server returned HTTP response code: 403 for URL: https://<s3 address>/builds/app.xml/app.xml
Why is it looking for app.xml/app.xml?

**Comment by Koire** [comment]
Still no luck, I made a trivial change to the code -- changed the title of the primary stage -- changed the version, ran "generateNativeInstaller", checked that the app.xml updated with the new version, uploaded it to s3, opened the app, and it was the same as previously.

**Comment by edvin** [comment]
Sorry for the late reply. If it's looking for app.xml/app.xml, you have added app.xml to your applicationUrl. The applicationUrl should only contain the base "folder" for the app. The launcher will add app.xml to the URL when needed to retrieve it.

**Comment by Koire** [comment]
Thanks, i figured that out, I'm having trouble now where if I don't clean
before building it will add the new build to app.xml but won't update.

**Comment by Koire** [comment]
Going to close this here because the deploy works as expected now, I will look into a way to authenticate and use Chris's idea to launch a native app to launcher.
