### ISSUE TITLE
can't run any fxlauncher commands (gradle)

### ISSUE THREAD

**Issue by Taximan** [edvin/fxlauncher#75]
Both on my project and on the demo project I get this error if I run generateNativeInstaller gradle command.

`> Could not resolve all dependencies for configuration ':internal_fxlauncher'.
   > Could not resolve no.tornado:fxlauncher:1.0.16.
     Required by:
         no.tornado:fxldemo-gradle:1.0
      > Could not resolve no.tornado:fxlauncher:1.0.16.
         > Could not get resource 'https://repo1.maven.org/maven2/no/tornado/fxlauncher/1.0.16/fxlauncher-1.0.16.pom'.
            > Could not GET 'https://repo1.maven.org/maven2/no/tornado/fxlauncher/1.0.16/fxlauncher-1.0.16.pom'.
               > Connection to https://repo1.maven.org refused
      > Could not resolve no.tornado:fxlauncher:1.0.16.
         > Could not get resource 'https://jcenter.bintray.com/no/tornado/fxlauncher/1.0.16/fxlauncher-1.0.16.pom'.
            > Could not GET 'https://jcenter.bintray.com/no/tornado/fxlauncher/1.0.16/fxlauncher-1.0.16.pom'.
               > Connection to https://jcenter.bintray.com refused`

I am also behind a corporate proxy if that matters though other packages work just fine.

**Comment by edvin** [comment]
It seems your corporate proxy is prohibiting you from accessing the maven central repo mirrors, so you need to work around this somehow :) Maybe you can add proxy parameters to the jvm as described here:

https://docs.oracle.com/javase/8/docs/technotes/guides/net/proxies.html

Hope this helps :)

**Comment by Taximan** [comment]
Well you were right. I didn't even expected the proxy to be an issue since I set it in intelij's settings and other packages seemed to work just fine.

If anyone fell for the same issue, to fix this I created a gradle.properties with the following content

`systemProp.http.proxyHost=<YOUR_HTTP_PROXY_HERE>
systemProp.http.proxyPort=<YOURS_HTTP_PROXY_PORT_HERE>
systemProp.https.proxyHost=<YOUR_HTTPS_PROXY_HERE>
systemProp.https.proxyPort=<YOURS_HTTPS_PROXY_PORT_HERE>

**Comment by edvin** [comment]
Great! Thanks for updating the ticket, I'm sure that will be useful to others.
