### ISSUE TITLE
Error during Application Environment Prepare phase

### ISSUE THREAD

**Issue by estebantcs** [edvin/fxlauncher#77]
Hi 
I created a Windows installer using FxLauncher Gradle plugin. After that I installed de app using the .exe file. the first time the app ran fine but the second time it throws this error:
java.lang.NullPointerException
	at fxlauncher.Launcher.launchAppFromManifest(Launcher.java:161)
	at fxlauncher.Launcher.lambda$start$0(Launcher.java:150)
	at java.lang.Thread.run(Thread.java:745)
Can U Help Please?

Note if i Run the fxLauncher.jar from the IDE  the app run fines

**Comment by edvin** [comment]
Can you send me a link to the published application and if possible the sources for your build file?

**Comment by estebantcs** [comment]
Thanks for your reply. I found the issue. i was closing the app in the wrong way. I just restartthe app and close it properly and issue resolved.

in the other hand, how can i change the native installer icon using gradle plugIn?

**Comment by edvin** [comment]
Great! I will expose an icon parameter to the Gradle plugin soon. I'm long over due with an update, just haven't had time to prioritize it lately. Hopefully I will get to it in a couple of days.

**Comment by edvin** [comment]
Actually, you can change the icon by supplying `-Bicon=path/to/icon` in the `javapackagerOptions` configuration option. This option is a `List<String>`. This is already available in version 1.0.16 of the plugin. Does that work for you?
