### ISSUE TITLE
fxLauncher in Windows 

### ISSUE THREAD

**Issue by albertoclarit** [edvin/fxlauncher#83]
Hi Edvin,

fxLauncher will update even though theres no new updates since the last run. 
See https://youtu.be/nHkkD-UgFbE

Any mistakes i made? The demo native installer works just fine.

Thanks

**Comment by albertoclarit** [comment]
Works OK in OSX

**Comment by MouseEvent** [comment]
Could you be missing the cache dir?

**Comment by MouseEvent** [comment]
Could you be missing the cache dir manifest attribute?

**Comment by albertoclarit** [comment]
Im using a native installer...I though the cache-dir option is not needed at this point ... anyways i will try that... hang on

**Comment by edvin** [comment]
It would be interesting to se the console output for the application. Can you start it from the command line and paste the log output? It could be related to the cache dir somehow, but I'd need the log to be sure.

**Comment by albertoclarit** [comment]
Hi guys... my App manifest is here 
http://cm.hisd3.com/app.xml  

Im running the native installers... theres no output if i run them in command line...

Though I observe this behavior.
 If I run `./gradlew deployApp`   and  `./gradlew generateNativeInstaller`
on OSX, the App will behave as expected.

But when I make the `gradlew generateNativeInstaller` on windows (since i already uploaded in the osx) ... the windows native bundle is always downloading.

I check their app.xml and they differ on <Application ts="???"  ...> line.

Does that matter?

**Comment by edvin** [comment]
That shouldn't matter, since ts is just the timestamp the manifest was created. I could add debugging support to the launcher so we can see what's going on. My problem is time, just don't have enough of it at the moment :(

**Comment by albertoclarit** [comment]
I was able to workaround the issue...

 I notice that if I have generated the native installer after i uploaded the dependencies... it will result into a loop which the native installer always downloads the dependencies

Workaround was to generate native installers first then deploy the app to the servers.

Thanks ...
