### ISSUE TITLE
Typo in --stopOnUpdateErrors option

### ISSUE THREAD

**Issue by mordechaim** [edvin/fxlauncher#84]
https://github.com/edvin/fxlauncher/blob/f1eae017036124a1183cc9facf435ee6230a5ab9/src/main/java/fxlauncher/AbstractLauncher.java#L266

There's an uppercase ``D`` in ``UpDate``.

**Comment by gcstang** [comment]
Submitted a fix and add a pull request.
Thank you for your find.
