### ISSUE TITLE
Problematic regex on LibraryFile OS specification

### ISSUE THREAD

**Issue by mordechaim** [edvin/fxlauncher#85]
https://github.com/edvin/fxlauncher/blob/f1eae017036124a1183cc9facf435ee6230a5ab9/src/main/java/fxlauncher/LibraryFile.java#L43

There are a 2 problems with this:

1. The extension dot isn't escaped, successfully matching  `lib-macajar`.
2. It's not anchored at the end of the string, successfully matching  ` lib-macajaring.jpg`.
3. It will only match jars, but fail on non jars. 

My advice would be to change it to:

	Pattern osPattern = Pattern.compile(".+-(linux|win|mac)\\.[^\\.]+$");

This will only match filenames where the os is given just before the extension.

**Comment by edvin** [comment]
I was a bit quick with this one for sure. Great. Would you like to file a PR or should I just add it? Thanks for your contribution!

**Comment by mordechaim** [comment]
I have a pending PR so do it yourself.

**Comment by edvin** [comment]
Done. I removed the escape for dot inside the range, no need to escape dot in ranges.
