### ISSUE TITLE
exe file missing

### ISSUE THREAD

**Issue by estebantcs** [edvin/fxlauncher#90]
Hi, i am using fxlauncher to generate a native installer for my javafx app.
i am using gradle plugin, when a i run the native installer task, the files are generate but there is not the exe files.

**Comment by edvin** [comment]
Can you post a tree listing of the build output folder?

**Comment by estebantcs** [comment]
inside Installer folder

![image](https://user-images.githubusercontent.com/16025028/30839578-78ffacc6-a238-11e7-94a7-bd405524275e.png)


Inside Bundle folder

![image](https://user-images.githubusercontent.com/16025028/30839586-88ca6a92-a238-11e7-8e3a-37f35e663b08.png)

Inside AppName folder

**Comment by estebantcs** [comment]
i found the problem, i forgot to  Inno Setup 5.5.1
