### ISSUE TITLE
Downloading Zip file using fxLauncher

### ISSUE THREAD

**Issue by varunsingh001** [edvin/fxlauncher#92]
We have a requirement to get zip file along with other dependencies during auto-update.
Manually updating manifest on server can do the job, but need this to be automated.

Is it possible to enable downloading/updating ZIP files along with dependencies without manual intervention?

**Comment by edvin** [comment]
Sorry for the late reply. Yes, there is a mechanism for that:

`--include-extensions` accepts a comma separated list of filename extensions to include of other resources from the build dir. By default it always includes jar,war.

You must just make sure those files are in the build dir as the `Create Manifest` step is running.
