### ISSUE TITLE
Question - Can this work with a swing application ?

### ISSUE THREAD

**Issue by martinm1000** [edvin/fxlauncher#98]
Hi,
I'm not ready to convert our swing application to java fx, but in the mean time, as WebStart is getting deprecated under Java 9+, can fxlauncher launch a **swing** application ?

If not, is support for Swing (or even plain simple main(String[] args) execution) possible ?

**Comment by edvin** [comment]
We already support console applications, so it would be pretty easy to adapt it to support a Swing application. You could even use it out of the box with a small wrapper. I haven't looked at the boot code in a while, but I think it should be fairly trivial to support Swing for sure :)

**Comment by martinm1000** [comment]
This is great news. But right now, could it work if I try launching a swing app ? If you already support console application, this might be enough already ?

**Comment by edvin** [comment]
Actually, you can launch a Swing app using the headless launcher, which basically just runs whatever main method you point it to. See more information in this thread:

https://github.com/edvin/fxlauncher/issues/73

I haven't even tried FXLauncher with Java 9 yet. I suspect it may work, it uses extremely few features of the JVM.

We'll take a closer look at specific Java 9 support either when bug reports are filed or when TornadoFX is converted to Java 9.

**Comment by martinm1000** [comment]
Thanks, I'll try fxlauncher in the near future !

**Comment by edvin** [comment]
Great! Let me know if you need help :)
